apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mushDb.applicationName" . }}
  labels:
    mushroomNode: main
spec:
  replicas: 1
  selector:
    matchLabels:
      mushroomNode: main
  template:
    metadata:
      name: {{ include "mushDb.applicationName" . }}-pod
      labels:
        mushroomNode: main
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: mush-api:latest
          imagePullPolicy: Never
          ports:
            - name: http-api
              containerPort: 80
          volumeMounts:
            - name: test-storage
              mountPath: "/tmp/k8sTesting"
            - name: mushroom-images-storage
              mountPath: "/pics"
          env:
            # TODO: delete next vars DIR_TO_CHECK and FILE_TO_CHECK later
            - name: "DIR_TO_CHECK"
              value: "/tmp/k8sTesting"
            - name: "FILE_TO_CHECK"
              value: "toCheck.txt"
            - name: "API_PORT"
              value: "80"
            - name: "MONGO_INITDB_USERNAME"
              value: {{ .Values.dbRoot.username }}
            - name: "MONGO_INITDB_PASSWORD"
              value: {{ .Values.dbRoot.password }}
            - name: "MONGO_INITDB_DATABASE"
              value: {{ .Values.dbName }}
            - name: "RFID_SECRET"
              value: {{ quote .Values.rfidSecret }}
            - name: "DB_HOST_PORT"
              value: {{ .Values.dbPort | default "27017" | quote }}
            - name: "DB_HOST_NAME"
              value: {{ quote .Values.dbhostname }}
            - name: "WEB_HOST_INTERNAL"
              value: {{ .Values.webserverInternalHost | default "localhost" | quote }}
            - name: "WEB_HOST_INTERNAL_PORT"
              value: {{ .Values.webserverInternalPort | default "3000" | quote }}
        - name: web
          image: mush-web:latest
          imagePullPolicy: Never
          ports:
            - name: http-web
              containerPort: 3000
        - name: mush-db
          image: mongo:8-noble
          imagePullPolicy: IfNotPresent
          args: ["--dbpath","/data/db"]
          ports:
            - name: dbport
              containerPort: 27017
          volumeMounts:
            - name: "mushroom-database-storage"
              mountPath: "/data/db"
            - name: "mongodb-scripts"
              mountPath: "/docker-entrypoint-initdb.d"
              readOnly: true
          env:
{{/*            - name: "MONGO_INITDB_ROOT_USERNAME"*/}}
{{/*              value: {{ .Values.dbRoot.username }}*/}}
{{/*            - name: "MONGO_INITDB_ROOT_PASSWORD"*/}}
{{/*              value: {{ .Values.dbRoot.username }}*/}}
{{/*            - name: "MONGO_INITDB_USERNAME"*/}}
{{/*              value: {{ .Values.dbUser.username }}*/}}
{{/*            - name: "MONGO_INITDB_PASSWORD"*/}}
{{/*              value: {{ .Values.dbUser.password }}*/}}
{{/*            - name: "MONGO_INITDB_DATABASE"*/}}
{{/*              value: {{ .Values.dbName }}*/}}
      volumes:
        - name: mongodb-scripts
          configMap:
            name: mongodb-configmap
            items:
              - key: ensure-users.js
                path: ensure-users.js
        - name: mushroom-database-storage
          persistentVolumeClaim:
            claimName: mushroom-database-storage
        - name: mushroom-images-storage
          persistentVolumeClaim:
            claimName: mushroom-images-storage
        - name: test-storage
          persistentVolumeClaim:
            claimName: test-storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mush-host-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
{{/*volumeBindingMode: WaitForFirstConsumer*/}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "init-pv"
  labels:
    type: "local"
spec:
  storageClassName: mush-host-sc
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: "/tmp/mush"
    type: "Directory"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "db-pv"
  labels:
    type: "local"
spec:
  storageClassName: mush-host-sc
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteMany"
  hostPath:
    path: {{ quote .Values.dbPath }}
    type: "DirectoryOrCreate"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "imgs-pv"
  labels:
    type: "local"
spec:
  storageClassName: mush-host-sc
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteMany"
  hostPath:
    path: {{ quote .Values.picsPath }}
    type: "DirectoryOrCreate"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "mushroom-database-init-script-dir"
spec:
  volumeName: "init-pv"
  storageClassName: mush-host-sc
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "mushroom-database-storage"
spec:
  volumeName: "db-pv"
  storageClassName: mush-host-sc
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "mushroom-images-storage"
spec:
  volumeName: "imgs-pv"
  storageClassName: mush-host-sc
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
---
# TODO: delete later
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "test-pv"
  labels:
    type: "local"
spec:
  storageClassName: mush-host-sc
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteMany"
  hostPath:
    path: "/tmp/testHost"
    type: "Directory"
---
# TODO: delete later
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "test-storage"
spec:
  storageClassName: mush-host-sc
  volumeName: "test-pv"
{{/*  storageClassName: "test-manual"*/}}
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"