kind: Service
apiVersion: v1
metadata:
  name: api
  labels:
    mushroomNode: main
spec:
  selector:
    mushroomNode: main
  ports:
    - name: http
      port: 80
      targetPort: http-api
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: web
  labels:
    mushroomNode: main
spec:
  selector:
    mushroomNode: main
  ports:
    - name: http
      port: 3000
      targetPort: http-web
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: db
  labels:
    mushroomNode: main
{{/*  annotations:*/}}
{{/*    version: v1.0*/}}
spec:
  selector:
    mushroomNode: main
  ports:
    - name: mongo
      port: 27017
      targetPort: dbport
  type: ClusterIP
---
### Define a Service for application
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mushDb.name" . }}-external-load-balancer
spec:
  selector:
    app:  {{ include "mushDb.applicationName" . }} # TODO: ok?
  ports:
    - name: tcp
      protocol: TCP
      port: 80         # exposed port number (TODO: ON WHAT?)
      targetPort: 80   # forworded port number into application (TODO: ON WHAT?)
{{/*      nodePort: 30080  # mapped port number in the cluster (TODO: ON WHAT?)*/}}
{{/*      nodePort: 30443   # mapped port number in the cluster (TODO: ON WHAT?)*/}}
  type: LoadBalancer