version: '3.8'
services:
  # Service to maintain cloudflare tunnel (because homelab is behind CGNAT)
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    environment:
      - TZ=America/New_York
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    networks:
      - mushNet
  # Main go api
  api:
    image: mush-api:latest
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./DockerfileApi
      tags:
        - "mush-api:latest"
    environment:
      PICS_PATH: "/images"
      API_PORT: "80"
      MAIN_API_EXTERNAL_PROTOCOL: ${MAIN_API_EXTERNAL_PROTOCOL:-http}
      MAIN_API_EXTERNAL_HOST: ${MAIN_API_EXTERNAL_HOST:-localhost}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME:?error}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD:?error}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:?error}
      ADMIN_USER: ${ADMIN_USER:?error}
      ADMIN_PASS: ${ADMIN_PASS:?error}
      RFID_SECRET: ${RFID_SECRET:?error}
      DB_HOST_PORT: "27017"
      DB_HOST_NAME: "mushdb"
      WEB_HOST_INTERNAL: "web"
      WEB_HOST_INTERNAL_PORT: "3000"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:?error}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:?error}
    volumes:
      - pictures:/images
    networks:
      - mushNet
  # React/Next.js webserver
#  web:
#    image: mush-web:latest
#    restart: unless-stopped
#    build:
#      context: ./rfid/client
#      dockerfile: ./Dockerfile
#      args:
#        MAIN_API_EXTERNAL_PROTOCOL: ${MAIN_API_EXTERNAL_PROTOCOL:-http}
#        MAIN_API_EXTERNAL_HOST: ${MAIN_API_EXTERNAL_HOST:-localhost}
#        MAIN_API_EXTERNAL_PORT: ${MAIN_API_EXTERNAL_PORT:-80}
#        MAIN_API_INTERNAL_HOST: "api"
#      tags:
#        - "mush-web:latest"
#    environment:
#      NEXT_PRIVATE_BASE_API_URL: "${MAIN_API_EXTERNAL_PROTOCOL:-http}://api"
#      NEXT_PUBLIC_BASE_API_URL: "${MAIN_API_EXTERNAL_PROTOCOL:-http}://${MAIN_API_EXTERNAL_HOST:-localhost}"
#     networks:
#       - mushNet
  # fungi database container
  mushdb:
    image: mongo:4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:?error}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:?error}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME:?error}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD:?error}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:?error}
    command: [--auth]
    volumes:
      - mongodb-data:/data/db
      - ./initDB:/docker-entrypoint-initdb.d
    networks:
      - mushNet
  # grafana service
#  grafana:
#    image: grafana/grafana:latest
#    restart: unless-stopped
#    volumes:
#      - grafana-data:/var/lib/grafana:rw
#    #ports:
#    #  - 3000:3000 # TODO: FIX
#    environment:
#      - GF_SERVER_ROOT_URL=http://localhost:3000 # TODO: Adjust if accessing from a different domain/IP
#      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:?error} # TODO: do
#      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:?error} # TODO: run with password
#      - GF_LOG_LEVEL=debug # TODO: debug vs info
#      #- GF_LOG_MODE="console"
#      - GF_PLUGINS_PREINSTALL=grafana-mongodb-datasource,grafana-worldmap-panel,grafana-clock-panel,grafana-piechart-panel
#      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
#    networks:
#      - mushNet
networks:
  mushNet:
    name: mushNet
volumes:
  pictures:
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_IMAGES_DIR:?error}
      o: bind
  mongodb-data:
#    driver: local
#    driver_opts:
#      type: none
#      device: ${LOCAL_DB_DIR:?error}
#      o: bind
  grafana-data:
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_GRAFANA_DIR:?error} # TODO: ADD
      o: bind
# configs:
#  config.json: # TODO: generate via template?
#    content: |
#      {
#        "cloudflare": [
#          {
#            "authentication": {
#              "api_token": "${CLOUDFLARE_API_TOKEN:?error}",
#            },
#            "zone_id": "${CLOUDFLARE_ZONE_ID:?error}",
#            "subdomains": [
#              {
#                "name": "",
#                "proxied": false
#              },
#              {
#                "name": "home",
#                "proxied": false
#              }
#            ]
#          }
#        ],
#        "a": false,
#        "aaaa": true,
#        "purgeUnknownRecords": true,
#        "ttl": 120
#      }