version: '3.8'
services:
  web:
    image: mush-web:latest
    restart: unless-stopped
    build:
      context: ./web
      dockerfile: ./Dockerfile-dev
      args:
        MAIN_API_EXTERNAL_PROTOCOL: ${MAIN_API_EXTERNAL_PROTOCOL:-https}
        MAIN_API_EXTERNAL_HOST: ${MAIN_API_EXTERNAL_HOST:-localhost}
        MAIN_API_EXTERNAL_PORT: ${MAIN_API_EXTERNAL_PORT:-443}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID?error}
      tags:
        - "mush-web:latest"
    environment:
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID?error}
      # TODO: ENSURE NEXT 2 ARE OK AND USE
#      NEXT_PRIVATE_BASE_API_URL: "http://api:8080"
#      NEXT_PUBLIC_BASE_API_URL: https://mush.appli.ng
      NEXT_PRIVATE_BASE_API_URL: "http://api:8080"
      NEXT_PUBLIC_DOMAIN: ${MAIN_API_EXTERNAL_HOST:-localhost}
      NEXT_PUBLIC_PORT: ${MAIN_API_EXTERNAL_PORT:-443}
      NEXT_PUBLIC_BASE_API_URL: ${MAIN_API_EXTERNAL_PROTOCOL:-https}://${MAIN_API_EXTERNAL_HOST:-localhost}
    networks:
      - mushNet
    depends_on:
      # TODO: ensure ok, may not need
      - api