version: '3.8'
services:
  web:
    image: mush-web-dev:latest
    restart: unless-stopped
    build:
      context: ./web
      dockerfile: ./Dockerfile-dev
      args:
        MAIN_API_EXTERNAL_PROTOCOL: ${MAIN_API_EXTERNAL_PROTOCOL:-https}
        MAIN_API_EXTERNAL_HOST: ${MAIN_API_EXTERNAL_HOST:-localhost}
        MAIN_API_EXTERNAL_PORT: ${MAIN_API_EXTERNAL_PORT:-443}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID?error}
      tags:
        - "mush-web-dev:latest"
    networks:
      - mushNet
    depends_on:
      - api