# DefaultValues for mushDb
nodeSelector: {
  mushroomNode: main
}

localPort: 80

dbPath: "/etc/fix/me"
picsPathAbsolute: "/etc/fix/me"
dbRoot:
  username: ""
  password: ""
dbUser:
  username: "" # TODO: FIXME
  password: "" # TODO: FIXME
dbName: "mushDb"
rfidSecret: "" # TODO: FIXME
externalhost: "your-external-hostname.com"  # TODO: FIXME?
applicationNameOverride: ""
# TODO: FIX!
# TODO: all new below!
dbhostname: "localhost"
dbPort: 27017
googleClientId: "CLIENT_ID_HERE"
googleClientSecret: "GOOGLE_CLIENT_SECRET_HERE"
