package main

import (
	"fmt"
	"github.com/reeceappling/goUtils/v2/utils/slices"
	"golang.org/x/exp/maps"
	"log"
	"os"
	"strings"
	"text/template"
)

func main() {
	// Define the data to be used in the template
	data := struct {
		mainCollTypes  map[string]mainCollInfo
		otherCollTypes map[string]otherCollInfo
	}{
		mainCollTypes:  mainCollTypes,
		otherCollTypes: otherCollTypes,
	}

	const interfacesTpl = `// Code generated by generator; DO NOT EDIT.
package rfid
var (
{{range $typ, $info := .mainCollTypes}}
	_ MainCollectionItem = &{{$typ}}{}"
{{end}}
{{range $typ, $info := .mainCollTypes}}
	_ geneticSource = &{{$typ}}{}"
{{end}}
)
`
	// The template for the new Go file
	const tpl = `// Code generated by generator; DO NOT EDIT.

package rfid

import (
	"go.mongodb.org/mongo-driver/mongo"
)
const (
{{range $typ, $info := .mainCollTypes}}
    {{$info.collConstName}} = {{$info.collName}}
    {{$info.entryTypeConstName}} = {{$info.entryTypeConstValue}}
{{end}}
{{range $typ, $info := .otherCollTypes}}
    {{$info.collConstName}} = {{$info.collName}}
{{end}}
)

{{range $typ, $info := .mainCollTypes}}
func ({{$info.receiver}} *{{$typ}}) SetPerms(field AclField) {
	{{$info.receiver}}.AclField = field
}

// TODO: DbId
// TODO: EntryType
// TODO: SourceType
// TODO: CollectionType
// TODO: Decode
{{end}}
{{range $typ, $info := .otherCollTypes}}
func ({{$info.receiver}} {{$typ}}) CollectionName() string {
	return {{$info.collConstName}}
}
// TODO: Decode
{{end}}


func Greet{{.Name}}() {
	fmt.Println("Hello from generated code!")
}
`

	// Create the output file
	f, err := os.Create("generated.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	// Parse and execute the template
	t := template.Must(template.New("generator").Parse(tpl))
	err = t.Execute(f, data)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("generated.go created")

	// Create the output file
	ff, err := os.Create("tempGenerated.go")
	if err != nil {
		log.Fatal(err)
	}
	defer ff.Close()

	// Parse and execute the template
	tt := template.Must(template.New("generator").Parse(interfacesTpl))
	err = tt.Execute(ff, data)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("tempGenerated.go created")
}

func generateAll() string {
	b := &strings.Builder{}
	writeTop(b)
	allConstants(b)
	fullValidateInterfacesArea(b)
	allCollItemMethods(b)

	return b.String()
}

type mainCollInfo struct {
	reciever            string
	entryTypeConstName  string
	entryTypeConstValue string
	collConstName       string
	collName            string
}

type otherCollInfo struct {
	reciever      string
	collConstName string
	collName      string
}

type methodInfo struct {
	sig     string
	bodyGen func(info mainCollInfo) string
}
type methodInfoForOther struct {
	sig     string
	bodyGen func(info otherCollInfo) string
}

func infoForO(reciever, collConstName, collConstValue string) otherCollInfo {
	return otherCollInfo{reciever, collConstName, collConstValue}
}

func infoFor(a, b, c, d, e string) mainCollInfo {
	return mainCollInfo{a, b, c, d, e}
}

var mainCollTypes = map[string]mainCollInfo{
	"Bag":             infoFor("b", "BagSourceType", "bag", "BagsCollectionName", "fruitingBags"),
	"Fruit":           infoFor("f", "FruitSourceType", "fruit", "FruitsCollName", "fruits"),
	"FruitingChamber": infoFor("f", "FruitingChamberSourceType", "fruitingChamber", "FruitingChamberCollectionName", "fruitingChambers"),
	"GrainJar":        infoFor("j", "GrainJarSourceType", "jar", "GrainJarCollectionName", "grainJars"),
	"LiquidCulture":   infoFor("l", "LcSourceType", "lc", "LCCollectionName", "LCJars"),
	"LcSyringe":       infoFor("lcs", "LcSyringeSourceType", "lcSyringe", "LcSyringeCollectionName", "lcSyringes"),
	"MSS":             infoFor("M", "MssSourceType", "mss", "MssCollectionName", "multisporeSyringes"),
	"Plate":           infoFor("p", "PlateSourceType", "plate", "PlatesCollectionName", "plates"),
	"PlugsJar":        infoFor("pl", "PlugSourceType", "plug", "PlugsCollectionName", "plugs"),
	"Slant":           infoFor("s", "SlantSourceType", "slant", "SlantsCollectionName", "slants"),
	"SporePrint":      infoFor("sp", "SporePrintSourceType", "sporePrint", "SporePrintCollectionName", "sporePrints"),
	"SporeSwab":       infoFor("sw", "SporeSwabSourceType", "swab", "SporeSwabCollectionName", "sporeSwabs"),
	"StasisTube":      infoFor("s", "StasisTubeSourceType", "stasisTube", "StasisTubeCollectionName", "stasisTubes"),
}
var otherCollTypes = map[string]otherCollInfo{
	"AgarBatch":       infoForO("batch", "AgarBatchCollectionName", "agarBatches"),
	"AgarRecipe":      infoForO("recipe", "AgarRecipesCollectionName", "agarRecipes"),
	"LcRecipe":        infoForO("recipe", "LcRecipesCollectionName", "lcRecipes"),
	"PCRun":           infoForO("run", "PcRunCollectionName", "pcRuns"),
	"Project":         infoForO("p", "ProjectsCollectionName", "Projects"),
	"Sale":            infoForO("s", "SalesCollectionName", "sales"),
	"Species":         infoForO("sp", "SpeciesCollectionName", "species"),
	"Subspecies":      infoForO("subsp", "SubspeciesCollectionName", "subspecies"),
	"SubstrateBatch":  infoForO("batch", "SubstrateBatchCollectionName", "substrateBatches"),
	"SubstrateRecipe": infoForO("recipe", "SubstrateRecipesCollectionName", "substrateRecipes"),
	"Transfer":        infoForO("t", "TransfersCollName", "transfers"),
	"User":            infoForO("u", "UserCollName", "users"),
}

var mainCollMethods = []methodInfo{
	entryTypeMethod,
	sourceTypeMethod, // TODO: likely get rid of
	collectionNameMethod,
	dbIdMethod,
	decodeMethod,

	// TODO: ADD MORE
}
var mainCollPtrMethods = []methodInfo{
	setPermsMethod,
	// TODO: ADD MORE
}
var otherCollMethods = []methodInfoForOther{
	otherCollectionNameMethod,
	decodeMethodOther,
	// TODO: ADD MORE?
}
var otherCollPtrMethods = []methodInfoForOther{
	// TODO: ADD MORE?
}

func allConstants(b *strings.Builder) {
	b.WriteString("\nconst (")
	for _, info := range mainCollTypes {
		col := fmt.Sprintf(`\t%s = "%s"\n"`, info.collConstName, info.collName)
		src := fmt.Sprintf(`\t%s = "%s"\n"`, info.entryTypeConstName, info.entryTypeConstValue)
		b.WriteString(col + src)
	}
	for _, info := range otherCollTypes {
		b.WriteString(fmt.Sprintf(`\t%s = "%s"\n"`, info.collConstName, info.collName))
	}
	b.WriteString(")\n")

}
func writeTop(b *strings.Builder) {
	// package
	b.WriteString("package rfid\n\nimport(\n")
	// imports
	for _, imp := range []string{
		"go.mongodb.org/mongo-driver/mongo",
	} {
		b.WriteString(fmt.Sprintf("\t\"%s\"\n", imp))
	}
	b.WriteString(")\n")
}

func allCollItemMethods(b *strings.Builder) {
	for typ, info := range mainCollTypes {
		genMainCollectionItem(b, typ, info)
	}
	for typ, info := range otherCollTypes {
		genOtherCollectionItem(b, typ, info)
	}
}

func genMainCollectionItem(b *strings.Builder, typ string, info mainCollInfo) {
	// Non-pointer Methods
	receiver := mainCollReceiver(typ, info)
	for _, methodToWrite := range mainCollMethods {
		b.WriteString(method(receiver, methodToWrite.sig, methodToWrite.bodyGen(info)))
	}
	// Pointer Methods
	ptrReceiver := mainCollPtrReceiver(typ, info)
	for _, methodToWrite := range mainCollPtrMethods {
		b.WriteString(method(ptrReceiver, methodToWrite.sig, methodToWrite.bodyGen(info)))
	}
}
func genOtherCollectionItem(b *strings.Builder, typ string, info otherCollInfo) {
	// Non-pointer Methods
	receiver := otherCollReceiver(typ, info)
	for _, methodToWrite := range otherCollMethods {
		b.WriteString(method(receiver, methodToWrite.sig, methodToWrite.bodyGen(info)))
	}
	// Pointer Methods
	ptrReceiver := otherCollPtrReceiver(typ, info)
	for _, methodToWrite := range otherCollPtrMethods {
		b.WriteString(method(ptrReceiver, methodToWrite.sig, methodToWrite.bodyGen(info)))
	}
}

func allOtherCollMethods(b *strings.Builder) {
	for typ, info := range mainCollTypes {
		receiver := mainCollPtrReceiver(typ, info)
		for _, methodToWrite := range []methodInfo{
			dbIdMethod,
			setPermsMethod,
			// TODO: ADD MORE
		} {
			b.WriteString(method(receiver, methodToWrite.sig, methodToWrite.bodyGen(info)))
		}
	}
}

func method(receiverText, signature, body string) string {
	return fmt.Sprintf("\nfunc %s %s {\n%s\n}\n", receiverText, signature, body)
}

func methodSignature(methodName string, methodArgs string, methodReturns string) string {
	methodReturnsResolved := ""
	if methodReturns != "" {
		methodReturnsResolved = "(" + methodReturns + ")"
	}
	return fmt.Sprintf(`%s(%s)%s
}!\n`, methodName, methodArgs, methodReturnsResolved)
}

func mainCollPtrReceiver(typeName string, info mainCollInfo) string {
	return fmt.Sprintf(`(%s *%s)`, info.reciever, typeName)
}
func mainCollReceiver(typeName string, info mainCollInfo) string {
	return fmt.Sprintf(`(%s %s)`, info.reciever, typeName)
}
func otherCollPtrReceiver(typeName string, info otherCollInfo) string {
	return fmt.Sprintf(`(%s *%s)`, info.reciever, typeName)
}
func otherCollReceiver(typeName string, info otherCollInfo) string {
	return fmt.Sprintf(`(%s %s)`, info.reciever, typeName)
}

//func methodWrapper(typeName string, info mainCollInfo, methodName string, methodArgs string, methodReturns string) func(body string) string {
//	methodReturnsResolved := ""
//	if methodReturns != "" {
//		methodReturnsResolved = "(" + methodReturns + ")"
//	}
//	return func(body string) string {
//		return fmt.Sprintf(`!\nfunc (%s *%s) %s(%s)%s {
//	%s
//}!\n`, info.reciever, typeName, methodName, methodArgs, methodReturnsResolved, body)
//	}
//}

var setPermsMethod = methodInfo{
	sig: methodSignature("SetPerms", "field AclField", ""),
	bodyGen: func(i mainCollInfo) string {
		return fmt.Sprintf(`%s.AclField = field`, i.reciever)
	},
}

var setPermsTpl = `func ({{.receiver}} *{{.typ}}) SetPerms(field AclField) {
	{{.receiver}}.AclField = field
}`

var dbIdMethod = methodInfo{
	sig: methodSignature("DbId", "", "MainCollectionId"),
	bodyGen: func(i mainCollInfo) string {
		return fmt.Sprintf(`return %s.Id`, i.reciever)
	},
}

var entryTypeMethod = methodInfo{ // TODO: likely get rid of and keep SourceType instead
	sig: methodSignature("EntryType", "", "string"),
	bodyGen: func(i mainCollInfo) string {
		return fmt.Sprintf(`return %s`, i.entryTypeConstName)
	},
}
var sourceTypeMethod = methodInfo{
	sig: methodSignature("SourceType", "", "string"),
	bodyGen: func(i mainCollInfo) string {
		return fmt.Sprintf(`return %s`, i.entryTypeConstName)
	},
}
var collectionNameMethod = methodInfo{
	sig: methodSignature("CollectionName", "", "string"),
	bodyGen: func(i mainCollInfo) string {
		return fmt.Sprintf(`return %s`, i.collConstName)
	},
}
var otherCollectionNameMethod = methodInfoForOther{
	sig: methodSignature("CollectionName", "", "string"),
	bodyGen: func(i otherCollInfo) string {
		return fmt.Sprintf(`return %s`, i.collConstName)
	},
}

var decodeMethod = methodInfo{
	sig: methodSignature("Decode", "encoded *mongo.SingleResult", "CollectionItem, error"),
	bodyGen: func(i mainCollInfo) string {
		return fmt.Sprintf(`out := %s
	err := decodeItem(&out, encoded)
	return out, err`, i.reciever)
	},
}
var decodeMethodOther = methodInfoForOther{
	sig: methodSignature("Decode", "encoded *mongo.SingleResult", "CollectionItem, error"),
	bodyGen: func(i otherCollInfo) string {
		return fmt.Sprintf(`out := %s
	err := decodeItem(&out, encoded)
	return out, err`, i.reciever)
	},
}

func validGeneticSourceStrs() []string {
	return slices.Map(maps.Keys(mainCollTypes), func(typ string) string {
		return "_ geneticSource = &" + typ + "{}"
	})
}
func validMainCollItemStrs() []string {
	return slices.Map(maps.Keys(mainCollTypes), func(typ string) string {
		return "_ MainCollectionItem = &" + typ + "{}"
	})
}

func writeValidateInterfacesGroup(b *strings.Builder, varStrs []string) {
	for _, str := range varStrs {
		_, err := b.WriteString(fmt.Sprintf(`!\n%s`, str))
		if err != nil {
			panic("writeValidateInterfacesArea failed body write")
		}
	}
}

func fullValidateInterfacesArea(b *strings.Builder) {
	_, err := b.WriteString("var (")
	if err != nil {
		panic("writeValidateInterfacesArea failed initial write")
	}
	for _, generatedGroup := range []func() []string{
		validMainCollItemStrs,
		validGeneticSourceStrs,
		// TODO: MORE!
	} {
		writeValidateInterfacesGroup(b, generatedGroup())
	}
	_, err = b.WriteString("\n)")
	if err != nil {
		panic("writeValidateInterfacesArea failed end write")
	}
}
