package main

import (
	"fmt"
	"log"
	"os"
	"text/template"
)

func main() {
	// Define the data to be used in the template
	data := struct {
		MainCollTypes  map[string]mainCollInfo
		OtherCollTypes map[string]otherCollInfo
	}{
		MainCollTypes:  mainCollTypes,
		OtherCollTypes: otherCollTypes,
	}
	const header = `// Code generated by goGenerator; DO NOT EDIT. To regenerate:
//go:generate goGenerator/buildAndGenerate.sh`

	const interfacesTpl = `package api

` + header + `

var ({{range $typ, $info := .MainCollTypes}}
	_ MainCollectionItem = &{{$typ}}{}{{end}}{{range $typ, $info := .MainCollTypes}}
	_ geneticSource = &{{$typ}}{}{{end}}{{range $typ, $info := .OtherCollTypes}}
	_ AltCollectionItem[{{$info.IdType}}] = &{{$typ}}{}{{end}}
)
`
	// The template for the new Go file
	const tpl = `package api

` + header + `
import (
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"context"
	"errors"
	"slices"
)

const (
	// Main collection entry constants
{{range $typ, $info := .MainCollTypes}}` + constCollNameTpl + `
    {{$info.EntryTypeConstName}} = "{{$info.EntryTypeConstValue}}"
{{end}}	// Alternate entry constants
{{range $typ, $info := .OtherCollTypes}}` + constCollNameTpl + `
{{end}})

// Functions
func mainCollMap(name string) (item MainCollectionItem, exists bool) {
	switch name {
	{{range $typ, $info := .MainCollTypes}}case "{{$info.EntryTypeConstValue}}": return &{{$typ}}{}, true
	{{end}}default: return nil, false
	}
}
func initializeDb(ctx context.Context) error {
	// Db will auto-create if it does not exist
	db := DbFrom(ctx)
	collNames, err := db.ListCollectionNames(ctx, bson.D{})
	if err != nil {
		return err
	}
	// Create all collections that don't already exist
	for _, name := range ` + collNameListTpl + ` {
		// Create if needed
		if !slices.Contains(collNames, name) {
			err = db.CreateCollection(ctx, name)
			if err != nil {
				return err
			}
		}
	}
	return nil
}
// TODO: get rid of one of the following two?
func typeForEntryType` + itemTypeFor + `}
func typeForSource` + itemTypeFor + `}

// Methods{{range $typ, $info := .MainCollTypes}}
` + setPermsMethodTpl + `
` + dbIdMethodTpl + `
` + entryTypeMethodTpl + `
` + sourceTypeMethodTpl + `
` + collectionNameMethodTpl + `
` + decodeMethodTpl + `
{{end}} // Alternate Collection Entry Types
{{range $typ, $info := .OtherCollTypes}}
` + collectionNameMethodTpl + `
` + decodeMethodTpl + `
{{if not $info.SpecialPermStyle}}` + setPermsMethodTpl + `{{end}}
{{end}}

`

	// Create the output file
	f, err := os.Create("generated.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	// Parse and execute the template
	err = template.Must(template.New("generator").Parse(tpl)).Execute(f, data)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("generated.go created")

	// Create the output file
	ff, err := os.Create("generatedInterfaces.go")
	if err != nil {
		log.Fatal(err)
	}
	defer ff.Close()

	// Parse and execute the template
	err = template.Must(template.New("generator").Parse(interfacesTpl)).Execute(ff, data)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("generatedInterfaces.go created")
}

const constCollNameTpl = `	{{$info.CollConstName}} = "{{$info.CollName}}"`

const decodeMethodTpl = `func ({{$info.Receiver}} {{$typ}}) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &{{$typ}}{}
	err := decodeItem(out, encoded)
	return out, err
}`
const collectionNameMethodTpl = `func ({{$info.Receiver}} {{$typ}}) CollectionName() string {
	return {{$info.CollConstName}}
}`
const setPermsMethodTpl = `
func ({{$info.Receiver}} *{{$typ}}) SetPerms(field AclField) {
	{{ if ne $info.Receiver "wj" }}{{$info.Receiver}}.AclField = field{{ end }}
}`
const dbIdMethodTpl = `func ({{$info.Receiver}} {{$typ}}) DbId() MainCollectionId {
	return {{$info.Receiver}}.Id
}`
const entryTypeMethodTpl = `func ({{$info.Receiver}} {{$typ}}) EntryType() string {
	return {{$info.EntryTypeConstName}}
}`
const sourceTypeMethodTpl = `func ({{$info.Receiver}} {{$typ}}) SourceType() string {
	return {{$info.EntryTypeConstName}}
}`

const collNameListTpl = `[]string{
//Main Collections
{{range $typ, $info := .MainCollTypes}}	{{$info.CollConstName}},
{{end}}	// Alt collections
{{range $typ, $info := .OtherCollTypes}}	{{$info.CollConstName}},
{{end}}
	}`

const itemTypeFor = `(src string) (MainCollectionItem, error) {
	out, exists := map[string]MainCollectionItem{
{{range $typ, $info := .MainCollTypes}}{{$info.EntryTypeConstName}}: &{{$typ}}{},
{{end}}
	}[src]
	if !exists {
		return nil, errors.New(src + " is not a valid entry type")
	}
	return out, nil`

type mainCollInfo struct {
	Receiver            string
	EntryTypeConstName  string
	EntryTypeConstValue string
	CollConstName       string
	CollName            string
}

type otherCollInfo struct {
	Receiver         string
	CollConstName    string
	CollName         string
	SpecialPermStyle bool   // false==Permissioned, true==user,project???
	IdType           string // Must either be AlternateCollectionId, or string (such as for users or projects)
}

func infoForO(reciever, collConstName, collConstValue, idType string) otherCollInfo {
	return otherCollInfo{reciever, collConstName, collConstValue, false, idType}
}

func infoFor(a, b, c, d, e string) mainCollInfo {
	return mainCollInfo{a, b, c, d, e}
}

var mainCollTypes = map[string]mainCollInfo{
	"Bag":             infoFor("b", "BagSourceType", "bag", "BagsCollectionName", "fruitingBags"),
	"Fruit":           infoFor("f", "FruitSourceType", "fruit", "FruitsCollName", "fruits"),
	"FruitingChamber": infoFor("f", "FruitingChamberSourceType", "fruitingChamber", "FruitingChamberCollectionName", "fruitingChambers"),
	"GrainJar":        infoFor("j", "GrainJarSourceType", "jar", "GrainJarCollectionName", "grainJars"),
	"LiquidCulture":   infoFor("l", "LcSourceType", "lc", "LCCollectionName", "LCJars"),
	"LcSyringe":       infoFor("lcs", "LcSyringeSourceType", "lcSyringe", "LcSyringeCollectionName", "lcSyringes"),
	"MSS":             infoFor("M", "MssSourceType", "mss", "MssCollectionName", "multisporeSyringes"),
	"Plate":           infoFor("p", "PlateSourceType", "plate", "PlatesCollectionName", "plates"),
	"PlugsJar":        infoFor("pl", "PlugSourceType", "plug", "PlugsCollectionName", "plugs"),
	"Slant":           infoFor("s", "SlantSourceType", "slant", "SlantsCollectionName", "slants"),
	"SporePrint":      infoFor("sp", "SporePrintSourceType", "sporePrint", "SporePrintCollectionName", "sporePrints"),
	"SporeSwab":       infoFor("sw", "SporeSwabSourceType", "swab", "SporeSwabCollectionName", "sporeSwabs"),
	"StasisTube":      infoFor("s", "StasisTubeSourceType", "stasisTube", "StasisTubeCollectionName", "stasisTubes"),
	"WaterJar":        infoFor("wj", "WaterJarsSourceType", "waterJar", "WaterJarsCollectionName", "waterJars"),
}
var otherCollTypes map[string]otherCollInfo

func createOtherCollTypes() map[string]otherCollInfo {
	out := map[string]otherCollInfo{
		"AgarBatch":       infoForO("batch", "AgarBatchCollectionName", "agarBatches", "AlternateCollectionId"),
		"GrainBatch":      infoForO("batch", "GrainBatchCollectionName", "grainBatches", "AlternateCollectionId"),
		"AgarRecipe":      infoForO("recipe", "AgarRecipesCollectionName", "agarRecipes", "AlternateCollectionId"), // TODO: or do we want string for name?
		"LcRecipe":        infoForO("recipe", "LcRecipesCollectionName", "lcRecipes", "AlternateCollectionId"),
		"PCRun":           infoForO("run", "PcRunCollectionName", "pcRuns", "AlternateCollectionId"),
		"Sale":            infoForO("s", "SalesCollectionName", "sales", "AlternateCollectionId"),
		"Species":         infoForO("sp", "SpeciesCollectionName", "species", "string"),
		"Subspecies":      infoForO("subsp", "SubspeciesCollectionName", "subspecies", "string"),
		"SubstrateBatch":  infoForO("batch", "SubstrateBatchCollectionName", "substrateBatches", "AlternateCollectionId"),
		"SubstrateRecipe": infoForO("recipe", "SubstrateRecipesCollectionName", "substrateRecipes", "AlternateCollectionId"),
		"Transfer":        infoForO("t", "TransfersCollName", "transfers", "AlternateCollectionId"),
		"User":            infoForO("u", "UserCollName", "users", "string"),
		"Project":         infoForO("p", "ProjectsCollectionName", "Projects", "string"),
	}
	// Set special perms types (user, project)
	for _, key := range []string{"User", "Project"} {
		temp := out[key]
		temp.SpecialPermStyle = true
		out[key] = temp
	}
	return out
}

func init() {
	otherCollTypes = createOtherCollTypes()
}
