import type { Metadata } from "next";
import "./global.css"; // Also includes postcss/tailwind
import "@/app/ui/global.css"
import "@/app/ui/mostRecentImage.css"
import "@/app/ui/flexedAreas.css"
import "@/app/ui/subform.css"
import "@/app/ui/topBar.css"
import "@/app/ui/onViewCreators.css"
import "@/app/ui/transferDisplay.css"
import "@/app/ui/listPage.css" // TODO: consider moving
import "@/app/ui/project.css" // TODO: consider moving
import { Geist, Geist_Mono } from "next/font/google"; // TODO: FIX

// TODO: ensure all ok

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
