---
# create namespace for Cloudflare DDNS container as 'cloudflare-ddns'
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "homelab-ddns.resolvedNamespace" . }}
---
apiVersion: v1
data:
  config.json: {{ tpl (.Files.Get "internal/cloudflareconfig.json.tpl") . | b64enc }}
kind: Secret
metadata:
  name: cloudflare-ddns
  namespace: {{ include "homelab-ddns.resolvedNamespace" . }}
---
apiVersion: apps/v1 # TODO: MAKE SURE ONLY OCCURS ON HOST!!!!!
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: {{ include "homelab-ddns.resolvedNamespace" . }}
spec:
  selector:
    matchLabels:
      app: cloudflare-ddns # TODO: ok???
  template:
    metadata:
      labels:
        app: cloudflare-ddns
        secret-name: cloudflare-ddns
    spec:
      containers:
        - name: cloudflare-ddns
          image: timothyjmiller/cloudflare-ddns:latest
          resources:
            limits:
              memory: '32Mi'
              cpu: '50m'
          env:
            - name: CONFIG_PATH
              value: '/etc/cloudflare-ddns/'
          volumeMounts:
            - mountPath: '/etc/cloudflare-ddns'
              name: cloudflare-ddns
              readOnly: true
      volumes:
        - name: cloudflare-ddns
          secret:
            secretName: cloudflare-ddns
