apiVersion: v1
kind: Service
metadata:
  name: {{ include "homelab-ddns.fullname" . }}
  namespace: {{ include "homelab-ddns.resolvedNamespace" . }} # TODO: is this ok?
  labels:
    {{- include "homelab-ddns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "homelab-ddns.selectorLabels" . | nindent 4 }}
