# sudo raspi-config and enable ssh on pi before allowing ansible to connect
# Note your Pi's local IP address by running hostname -I.
# TODO: Copy your computer's SSH key to the Pi: ssh-copy-id username@your_pi_ip
[mainServer] # TODO: fix ip! fix username!
192.168.1.100 ansible_user=your_pi_username
[pi] # TODO: fix ip!
192.168.1.100 ansible_user=your_pi_username
# TODO: verify comms with pi via: ansible pi -i inventory.ini -m ping