package rfid

// Code generated by goGenerator; DO NOT EDIT. To regenerate:
//
//go:generate goGenerator/buildAndGenerate.sh

var (
	_ MainCollectionItem                       = &Bag{}
	_ MainCollectionItem                       = &Fruit{}
	_ MainCollectionItem                       = &FruitingChamber{}
	_ MainCollectionItem                       = &GrainJar{}
	_ MainCollectionItem                       = &LcSyringe{}
	_ MainCollectionItem                       = &LiquidCulture{}
	_ MainCollectionItem                       = &MSS{}
	_ MainCollectionItem                       = &Plate{}
	_ MainCollectionItem                       = &PlugsJar{}
	_ MainCollectionItem                       = &Slant{}
	_ MainCollectionItem                       = &SporePrint{}
	_ MainCollectionItem                       = &SporeSwab{}
	_ MainCollectionItem                       = &StasisTube{}
	_ geneticSource                            = &Bag{}
	_ geneticSource                            = &Fruit{}
	_ geneticSource                            = &FruitingChamber{}
	_ geneticSource                            = &GrainJar{}
	_ geneticSource                            = &LcSyringe{}
	_ geneticSource                            = &LiquidCulture{}
	_ geneticSource                            = &MSS{}
	_ geneticSource                            = &Plate{}
	_ geneticSource                            = &PlugsJar{}
	_ geneticSource                            = &Slant{}
	_ geneticSource                            = &SporePrint{}
	_ geneticSource                            = &SporeSwab{}
	_ geneticSource                            = &StasisTube{}
	_ AltCollectionItem[AlternateCollectionId] = &AgarBatch{}
	_ AltCollectionItem[AlternateCollectionId] = &AgarRecipe{}
	_ AltCollectionItem[AlternateCollectionId] = &LcRecipe{}
	_ AltCollectionItem[AlternateCollectionId] = &PCRun{}
	_ AltCollectionItem[string]                = &Project{}
	_ AltCollectionItem[AlternateCollectionId] = &Sale{}
	_ AltCollectionItem[string]                = &Species{}
	_ AltCollectionItem[string]                = &Subspecies{}
	_ AltCollectionItem[AlternateCollectionId] = &SubstrateBatch{}
	_ AltCollectionItem[AlternateCollectionId] = &SubstrateRecipe{}
	_ AltCollectionItem[AlternateCollectionId] = &Transfer{}
	_ AltCollectionItem[string]                = &User{}
)
