// Code generated by goGenerator; DO NOT EDIT.
// To regenerate: go build -o goGenerator/mygenerator ./goGenerator
//go:generate ./goGenerator/mygenerator

package rfid

import (
	"go.mongodb.org/mongo-driver/mongo"
)
const (

    BagsCollectionName = "fruitingBags"
    BagSourceType = "bag"

    FruitsCollName = "fruits"
    FruitSourceType = "fruit"

    FruitingChamberCollectionName = "fruitingChambers"
    FruitingChamberSourceType = "fruitingChamber"

    GrainJarCollectionName = "grainJars"
    GrainJarSourceType = "jar"

    LcSyringeCollectionName = "lcSyringes"
    LcSyringeSourceType = "lcSyringe"

    LCCollectionName = "LCJars"
    LcSourceType = "lc"

    MssCollectionName = "multisporeSyringes"
    MssSourceType = "mss"

    PlatesCollectionName = "plates"
    PlateSourceType = "plate"

    PlugsCollectionName = "plugs"
    PlugSourceType = "plug"

    SlantsCollectionName = "slants"
    SlantSourceType = "slant"

    SporePrintCollectionName = "sporePrints"
    SporePrintSourceType = "sporePrint"

    SporeSwabCollectionName = "sporeSwabs"
    SporeSwabSourceType = "swab"

    StasisTubeCollectionName = "stasisTubes"
    StasisTubeSourceType = "stasisTube"


    AgarBatchCollectionName = "agarBatches"

    AgarRecipesCollectionName = "agarRecipes"

    LcRecipesCollectionName = "lcRecipes"

    PcRunCollectionName = "pcRuns"

    ProjectsCollectionName = "Projects"

    SalesCollectionName = "sales"

    SpeciesCollectionName = "species"

    SubspeciesCollectionName = "subspecies"

    SubstrateBatchCollectionName = "substrateBatches"

    SubstrateRecipesCollectionName = "substrateRecipes"

    TransfersCollName = "transfers"

    UserCollName = "users"

)


func (b *Bag) SetPerms(field AclField) {
	b.AclField = field
}
func (b Bag) DbId() MainCollectionId {
	return b.Id
}
func (b Bag) EntryType() string {
	return BagSourceType // TODO: delete???
}
func (b Bag) SourceType() string {
	return BagSourceType
}
func (b Bag) CollectionName() string {
	return BagsCollectionName
}
func (b Bag) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := Bag{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (f *Fruit) SetPerms(field AclField) {
	f.AclField = field
}
func (f Fruit) DbId() MainCollectionId {
	return f.Id
}
func (f Fruit) EntryType() string {
	return FruitSourceType // TODO: delete???
}
func (f Fruit) SourceType() string {
	return FruitSourceType
}
func (f Fruit) CollectionName() string {
	return FruitsCollName
}
func (f Fruit) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := Fruit{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (f *FruitingChamber) SetPerms(field AclField) {
	f.AclField = field
}
func (f FruitingChamber) DbId() MainCollectionId {
	return f.Id
}
func (f FruitingChamber) EntryType() string {
	return FruitingChamberSourceType // TODO: delete???
}
func (f FruitingChamber) SourceType() string {
	return FruitingChamberSourceType
}
func (f FruitingChamber) CollectionName() string {
	return FruitingChamberCollectionName
}
func (f FruitingChamber) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := FruitingChamber{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (j *GrainJar) SetPerms(field AclField) {
	j.AclField = field
}
func (j GrainJar) DbId() MainCollectionId {
	return j.Id
}
func (j GrainJar) EntryType() string {
	return GrainJarSourceType // TODO: delete???
}
func (j GrainJar) SourceType() string {
	return GrainJarSourceType
}
func (j GrainJar) CollectionName() string {
	return GrainJarCollectionName
}
func (j GrainJar) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := GrainJar{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (lcs *LcSyringe) SetPerms(field AclField) {
	lcs.AclField = field
}
func (lcs LcSyringe) DbId() MainCollectionId {
	return lcs.Id
}
func (lcs LcSyringe) EntryType() string {
	return LcSyringeSourceType // TODO: delete???
}
func (lcs LcSyringe) SourceType() string {
	return LcSyringeSourceType
}
func (lcs LcSyringe) CollectionName() string {
	return LcSyringeCollectionName
}
func (lcs LcSyringe) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := LcSyringe{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (l *LiquidCulture) SetPerms(field AclField) {
	l.AclField = field
}
func (l LiquidCulture) DbId() MainCollectionId {
	return l.Id
}
func (l LiquidCulture) EntryType() string {
	return LcSourceType // TODO: delete???
}
func (l LiquidCulture) SourceType() string {
	return LcSourceType
}
func (l LiquidCulture) CollectionName() string {
	return LCCollectionName
}
func (l LiquidCulture) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := LiquidCulture{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (M *MSS) SetPerms(field AclField) {
	M.AclField = field
}
func (M MSS) DbId() MainCollectionId {
	return M.Id
}
func (M MSS) EntryType() string {
	return MssSourceType // TODO: delete???
}
func (M MSS) SourceType() string {
	return MssSourceType
}
func (M MSS) CollectionName() string {
	return MssCollectionName
}
func (M MSS) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := MSS{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (p *Plate) SetPerms(field AclField) {
	p.AclField = field
}
func (p Plate) DbId() MainCollectionId {
	return p.Id
}
func (p Plate) EntryType() string {
	return PlateSourceType // TODO: delete???
}
func (p Plate) SourceType() string {
	return PlateSourceType
}
func (p Plate) CollectionName() string {
	return PlatesCollectionName
}
func (p Plate) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := Plate{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (pl *PlugsJar) SetPerms(field AclField) {
	pl.AclField = field
}
func (pl PlugsJar) DbId() MainCollectionId {
	return pl.Id
}
func (pl PlugsJar) EntryType() string {
	return PlugSourceType // TODO: delete???
}
func (pl PlugsJar) SourceType() string {
	return PlugSourceType
}
func (pl PlugsJar) CollectionName() string {
	return PlugsCollectionName
}
func (pl PlugsJar) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := PlugsJar{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (s *Slant) SetPerms(field AclField) {
	s.AclField = field
}
func (s Slant) DbId() MainCollectionId {
	return s.Id
}
func (s Slant) EntryType() string {
	return SlantSourceType // TODO: delete???
}
func (s Slant) SourceType() string {
	return SlantSourceType
}
func (s Slant) CollectionName() string {
	return SlantsCollectionName
}
func (s Slant) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := Slant{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (sp *SporePrint) SetPerms(field AclField) {
	sp.AclField = field
}
func (sp SporePrint) DbId() MainCollectionId {
	return sp.Id
}
func (sp SporePrint) EntryType() string {
	return SporePrintSourceType // TODO: delete???
}
func (sp SporePrint) SourceType() string {
	return SporePrintSourceType
}
func (sp SporePrint) CollectionName() string {
	return SporePrintCollectionName
}
func (sp SporePrint) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := SporePrint{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (sw *SporeSwab) SetPerms(field AclField) {
	sw.AclField = field
}
func (sw SporeSwab) DbId() MainCollectionId {
	return sw.Id
}
func (sw SporeSwab) EntryType() string {
	return SporeSwabSourceType // TODO: delete???
}
func (sw SporeSwab) SourceType() string {
	return SporeSwabSourceType
}
func (sw SporeSwab) CollectionName() string {
	return SporeSwabCollectionName
}
func (sw SporeSwab) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := SporeSwab{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (s *StasisTube) SetPerms(field AclField) {
	s.AclField = field
}
func (s StasisTube) DbId() MainCollectionId {
	return s.Id
}
func (s StasisTube) EntryType() string {
	return StasisTubeSourceType // TODO: delete???
}
func (s StasisTube) SourceType() string {
	return StasisTubeSourceType
}
func (s StasisTube) CollectionName() string {
	return StasisTubeCollectionName
}
func (s StasisTube) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := StasisTube{}
	err := decodeItem(&out, encoded)
	return out, err
}


func (batch AgarBatch) CollectionName() string {
	return AgarBatchCollectionName
}
func (batch AgarBatch) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := AgarBatch{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (recipe AgarRecipe) CollectionName() string {
	return AgarRecipesCollectionName
}
func (recipe AgarRecipe) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := AgarRecipe{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (recipe LcRecipe) CollectionName() string {
	return LcRecipesCollectionName
}
func (recipe LcRecipe) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := LcRecipe{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (run PCRun) CollectionName() string {
	return PcRunCollectionName
}
func (run PCRun) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := PCRun{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (p Project) CollectionName() string {
	return ProjectsCollectionName
}
func (p Project) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := Project{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (s Sale) CollectionName() string {
	return SalesCollectionName
}
func (s Sale) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := Sale{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (sp Species) CollectionName() string {
	return SpeciesCollectionName
}
func (sp Species) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := Species{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (subsp Subspecies) CollectionName() string {
	return SubspeciesCollectionName
}
func (subsp Subspecies) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := Subspecies{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (batch SubstrateBatch) CollectionName() string {
	return SubstrateBatchCollectionName
}
func (batch SubstrateBatch) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := SubstrateBatch{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (recipe SubstrateRecipe) CollectionName() string {
	return SubstrateRecipesCollectionName
}
func (recipe SubstrateRecipe) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := SubstrateRecipe{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (t Transfer) CollectionName() string {
	return TransfersCollName
}
func (t Transfer) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := Transfer{}
	err := decodeItem(&out, encoded)
	return out, err
}

func (u User) CollectionName() string {
	return UserCollName
}
func (u User) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := User{}
	err := decodeItem(&out, encoded)
	return out, err
}


