---
# create namespace for Cloudflare DDNS container as 'cloudflare-ddns'
apiVersion: v1
kind: Namespace
metadata:
  name: homelab-ddns
---
apiVersion: v1
kind: Secret
data:
  config.json: {{ tpl (.Files.Get "internal/cloudflareconfig.json.tpl") . | b64enc }}
metadata:
  name: cloudflare-ddns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
spec:
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
        secret-name: cloudflare-ddns
    spec:
      containers:
        - name: cloudflare-ddns
          image: timothyjmiller/cloudflare-ddns:latest
          resources:
            limits:
              memory: '32Mi'
              cpu: '50m'
          env:
            - name: CONFIG_PATH
              value: '/etc/cloudflare-ddns/'
          volumeMounts:
            - mountPath: '/etc/cloudflare-ddns'
              name: cloudflare-ddns
              readOnly: true
      volumes:
        - name: cloudflare-ddns
          secret:
            secretName: cloudflare-ddns
