apiVersion: v1
kind: Service
metadata:
  name: {{ include "homelab-ddns.fullname" . }}
  labels:
    {{- include "homelab-ddns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP

  selector:
    {{- include "homelab-ddns.selectorLabels" . | nindent 4 }}
