apiVersion: apps/v1
kind: Deployment
metadata:
  name: mushrooms # TODO: ok????
  labels:
    app: {{ include "mushDb.applicationName" . }}
spec:
  replicas: 1
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      nodetype: main # TODO: OK???? --------------------------- MATCH MAIN NODE ONLY!!!!!*/}}
  template:
    metadata:
      name: {{ include "mushDb.applicationName" . }}-pod
      namespace: {{ include "mushDb.resolvedNamespace" . }}
      labels:
        app: {{ include "mushDb.applicationName" . }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: mushApi # TODO: FIX FOR API
          imagePullPolicy: Never
          ports:
            - name: http-api
              containerPort: 80
            - name: https-api
              containerPort: 443
          volumeMounts:
            - name: mushroom-images-storage
              mountPath: /pics
            - name: tls-files
              mountPath: /tls # TODO: FIX!-------------------------
          env:
            - name: MONGO_INITDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-user-auth
                  key: username
            - name: MONGO_INITDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user-auth
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.dbName }}
            - name: RFID_SECRET
              valueFrom:
                secretKeyRef:
                  name: rfid-auth
                  key: value
            - name: SERVER_CERT_FILENAME
              value: {{ .Values.server.cert.filename }}
            - name: SERVER_KEY_FILENAME
              value: {{ .Values.server.key.filename }}

        - name: web
          image: mushWeb
          imagePullPolicy: Never
          ports:
            - name: http-web
              containerPort: 3000
        - name: mushDb
          image: mongo:8-noble # TODO: version!
          imagePullPolicy: IfNotPresent
          command: [ 'mongod' ]
          ports:
            - name: dbport
              containerPort: 27017
          volumeMounts:
            - name: mushroom-database-storage
              mountPath: /data/db
            - name: mushroom-database-init-script
              mountPath: /docker-entrypoint-initdb.d/mongo-init.js
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-root-auth
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-root-auth
                  key: password
            - name: MONGO_INITDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-user-auth
                  key: username
            - name: MONGO_INITDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user-auth
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.dbName }}
      volumes:
        - name: mushroom-database-storage
          hostPath:
            - path: {{ .Values.dbPath }}
              type: DirectoryOrCreate
        - name: mushroom-images-storage
          hostPath:
            - path: {{ .Values.picsPath }}
              type: DirectoryOrCreate
        - name: tls-files
          hostPath:
            - path: {{ .Values.sslDir }}
              type: DirectoryOrCreate