apiVersion: v1
kind: Secret
metadata:
  name: db-root-auth
  namespace: {{ include "mushDb.name" . }}
type: Opaque
data:
  username: {{ .Values.dbRoot.username }}
  password: {{ .Values.dbRoot.password }}
immutable: true
---
apiVersion: v1
kind: Secret
metadata:
  name: db-user-auth
  namespace: {{ include "mushDb.resolvedNamespace" . }}
type: Opaque
data:
  username: {{ .Values.dbUser.username }}
  password: {{ .Values.dbUser.password }}
immutable: true
---
apiVersion: v1
kind: Secret
metadata:
  name: rfid-auth
  namespace: {{ include "mushDb.resolvedNamespace" . }}
type: Opaque
data:
  secret: {{ .Values.rfidSecret }}