apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-ingress
  annotations:
    # Next line should match issuer
    cert-manager.io/cluster-issuer: lets-encrypt
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public
  tls:
    - hosts:
        - home.appli.ng
      secretName: http-ingress-tls
  rules:
    - host: home.appli.ng
      http:
        paths:
          - path: /
            # TODO: next line WAS Exact
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80


