# syntax=docker.io/docker/dockerfile:1

FROM node:18-alpine AS base

# Step 1. Rebuild the source code only when needed
FROM base AS builder

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
# Omit --production flag for TypeScript devDependencies # TODO: ?????????
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
  # Allow install without lockfile, so example works even without Node.js installed locally
  else echo "Warning: Lockfile not found. It is recommended to commit lockfiles to version control." && yarn install; \
  fi

COPY src ./src
COPY public ./public
COPY next.config.ts .
COPY tsconfig.json .

# Environment variables must be present at build time
# https://github.com/vercel/next.js/discussions/14030
ARG MAIN_API_EXTERNAL_HOST=home.appli.ng
ARG MAIN_API_EXTERNAL_PROTOCOL=https
ARG MAIN_API_EXTERNAL_PORT=443
ARG MAIN_API_INTERNAL_HOST=api
ARG GOOGLE_CLIENT_ID=badIdInDockerfile
# TODO: api.namespace.svc.cluster.local TODO: FIX
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV NEXT_PRIVATE_BASE_API_URL=http://api:8080
ENV NEXT_PUBLIC_BASE_API_URL=https://mush.appli.ng
# TODO: was http

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at build time # TODO: CONSIDER
# ENV NEXT_TELEMETRY_DISABLED 1

CMD ["npm", "run", "dev"]