// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/reeceappling/mushDb/api"
	"github.com/reeceappling/pi-pn532-i2c-Ntag21x-ws/v2/websocketSessions/shared"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReadWriteService creates a new instance of MockReadWriteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadWriteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadWriteService {
	mock := &MockReadWriteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReadWriteService is an autogenerated mock type for the ReadWriteService type
type MockReadWriteService struct {
	mock.Mock
}

type MockReadWriteService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadWriteService) EXPECT() *MockReadWriteService_Expecter {
	return &MockReadWriteService_Expecter{mock: &_m.Mock}
}

// ReadRfid provides a mock function for the type MockReadWriteService
func (_mock *MockReadWriteService) ReadRfid(ctx context.Context, readerName shared.RfidReaderName) ([8]byte, error) {
	ret := _mock.Called(ctx, readerName)

	if len(ret) == 0 {
		panic("no return value specified for ReadRfid")
	}

	var r0 [8]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.RfidReaderName) ([8]byte, error)); ok {
		return returnFunc(ctx, readerName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.RfidReaderName) [8]byte); ok {
		r0 = returnFunc(ctx, readerName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([8]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.RfidReaderName) error); ok {
		r1 = returnFunc(ctx, readerName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadWriteService_ReadRfid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadRfid'
type MockReadWriteService_ReadRfid_Call struct {
	*mock.Call
}

// ReadRfid is a helper method to define mock.On call
//   - ctx context.Context
//   - readerName shared.RfidReaderName
func (_e *MockReadWriteService_Expecter) ReadRfid(ctx any, readerName any) *MockReadWriteService_ReadRfid_Call {
	return &MockReadWriteService_ReadRfid_Call{Call: _e.mock.On("ReadRfid", ctx, readerName)}
}

func (_c *MockReadWriteService_ReadRfid_Call) Run(run func(ctx context.Context, readerName shared.RfidReaderName)) *MockReadWriteService_ReadRfid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.RfidReaderName
		if args[1] != nil {
			arg1 = args[1].(shared.RfidReaderName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReadWriteService_ReadRfid_Call) Return(bytes [8]byte, err error) *MockReadWriteService_ReadRfid_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockReadWriteService_ReadRfid_Call) RunAndReturn(run func(ctx context.Context, readerName shared.RfidReaderName) ([8]byte, error)) *MockReadWriteService_ReadRfid_Call {
	_c.Call.Return(run)
	return _c
}

// WriteRfid provides a mock function for the type MockReadWriteService
func (_mock *MockReadWriteService) WriteRfid(ctx context.Context, readerName shared.RfidReaderName, id api.MainCollectionId) error {
	ret := _mock.Called(ctx, readerName, id)

	if len(ret) == 0 {
		panic("no return value specified for WriteRfid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.RfidReaderName, api.MainCollectionId) error); ok {
		r0 = returnFunc(ctx, readerName, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReadWriteService_WriteRfid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteRfid'
type MockReadWriteService_WriteRfid_Call struct {
	*mock.Call
}

// WriteRfid is a helper method to define mock.On call
//   - ctx context.Context
//   - readerName shared.RfidReaderName
//   - id api.MainCollectionId
func (_e *MockReadWriteService_Expecter) WriteRfid(ctx any, readerName any, id any) *MockReadWriteService_WriteRfid_Call {
	return &MockReadWriteService_WriteRfid_Call{Call: _e.mock.On("WriteRfid", ctx, readerName, id)}
}

func (_c *MockReadWriteService_WriteRfid_Call) Run(run func(ctx context.Context, readerName shared.RfidReaderName, id api.MainCollectionId)) *MockReadWriteService_WriteRfid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.RfidReaderName
		if args[1] != nil {
			arg1 = args[1].(shared.RfidReaderName)
		}
		var arg2 api.MainCollectionId
		if args[2] != nil {
			arg2 = args[2].(api.MainCollectionId)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReadWriteService_WriteRfid_Call) Return(err error) *MockReadWriteService_WriteRfid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReadWriteService_WriteRfid_Call) RunAndReturn(run func(ctx context.Context, readerName shared.RfidReaderName, id api.MainCollectionId) error) *MockReadWriteService_WriteRfid_Call {
	_c.Call.Return(run)
	return _c
}
