package api

// Code generated by goGenerator; DO NOT EDIT. To regenerate:
//go:generate goGenerator/buildAndGenerate.sh
import (
	"context"
	"errors"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"slices"
)

const (
	// Main collection entry constants
	BagsCollectionName            = "fruitingBags"
	BagSourceType                 = "bag"
	FruitsCollName                = "fruits"
	FruitSourceType               = "fruit"
	FruitingChamberCollectionName = "fruitingChambers"
	FruitingChamberSourceType     = "fruitingChamber"
	GrainJarCollectionName        = "grainJars"
	GrainJarSourceType            = "jar"
	LcSyringeCollectionName       = "lcSyringes"
	LcSyringeSourceType           = "lcSyringe"
	LCCollectionName              = "LCJars"
	LcSourceType                  = "lc"
	MssCollectionName             = "multisporeSyringes"
	MssSourceType                 = "mss"
	PlatesCollectionName          = "plates"
	PlateSourceType               = "plate"
	PlugsCollectionName           = "plugs"
	PlugSourceType                = "plug"
	SlantsCollectionName          = "slants"
	SlantSourceType               = "slant"
	SporePrintCollectionName      = "sporePrints"
	SporePrintSourceType          = "sporePrint"
	SporeSwabCollectionName       = "sporeSwabs"
	SporeSwabSourceType           = "swab"
	StasisTubeCollectionName      = "stasisTubes"
	StasisTubeSourceType          = "stasisTube"
	WaterJarsCollectionName       = "waterJars"
	WaterJarsSourceType           = "waterJar"
	// Alternate entry constants
	AgarBatchCollectionName        = "agarBatches"
	AgarRecipesCollectionName      = "agarRecipes"
	GrainBatchCollectionName       = "grainBatches"
	LcRecipesCollectionName        = "lcRecipes"
	PcRunCollectionName            = "pcRuns"
	ProjectsCollectionName         = "Projects"
	SalesCollectionName            = "sales"
	SpeciesCollectionName          = "species"
	SubspeciesCollectionName       = "subspecies"
	SubstrateBatchCollectionName   = "substrateBatches"
	SubstrateRecipesCollectionName = "substrateRecipes"
	TransfersCollName              = "transfers"
	UserCollName                   = "users"
)

// Functions
func mainCollMap(name string) (item MainCollectionItem, exists bool) {
	switch name {
	case "bag":
		return &Bag{}, true
	case "fruit":
		return &Fruit{}, true
	case "fruitingChamber":
		return &FruitingChamber{}, true
	case "jar":
		return &GrainJar{}, true
	case "lcSyringe":
		return &LcSyringe{}, true
	case "lc":
		return &LiquidCulture{}, true
	case "mss":
		return &MSS{}, true
	case "plate":
		return &Plate{}, true
	case "plug", "plugs":
		return &PlugsJar{}, true
	case "slant":
		return &Slant{}, true
	case "sporePrint":
		return &SporePrint{}, true
	case "swab":
		return &SporeSwab{}, true
	case "stasisTube":
		return &StasisTube{}, true
	case "waterJar":
		return &WaterJar{}, true
	default:
		return nil, false
	}
}
func initializeDb(ctx context.Context) error {
	// Db will auto-create if it does not exist
	db := DbFrom(ctx)
	collNames, err := db.ListCollectionNames(ctx, bson.D{})
	if err != nil {
		return err
	}
	// Create all collections that don't already exist
	for _, name := range []string{
		//Main Collections
		BagsCollectionName,
		FruitsCollName,
		FruitingChamberCollectionName,
		GrainJarCollectionName,
		LcSyringeCollectionName,
		LCCollectionName,
		MssCollectionName,
		PlatesCollectionName,
		PlugsCollectionName,
		SlantsCollectionName,
		SporePrintCollectionName,
		SporeSwabCollectionName,
		StasisTubeCollectionName,
		WaterJarsCollectionName,
		// Alt collections
		AgarBatchCollectionName,
		AgarRecipesCollectionName,
		GrainBatchCollectionName,
		LcRecipesCollectionName,
		PcRunCollectionName,
		ProjectsCollectionName,
		SalesCollectionName,
		SpeciesCollectionName,
		SubspeciesCollectionName,
		SubstrateBatchCollectionName,
		SubstrateRecipesCollectionName,
		TransfersCollName,
		UserCollName,
	} {
		// Create if needed
		if !slices.Contains(collNames, name) {
			err = db.CreateCollection(ctx, name)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// TODO: get rid of one of the following two?
func typeForEntryType(src string) (MainCollectionItem, error) {
	out, exists := map[string]MainCollectionItem{
		BagSourceType:             &Bag{},
		FruitSourceType:           &Fruit{},
		FruitingChamberSourceType: &FruitingChamber{},
		GrainJarSourceType:        &GrainJar{},
		LcSyringeSourceType:       &LcSyringe{},
		LcSourceType:              &LiquidCulture{},
		MssSourceType:             &MSS{},
		PlateSourceType:           &Plate{},
		PlugSourceType:            &PlugsJar{},
		SlantSourceType:           &Slant{},
		SporePrintSourceType:      &SporePrint{},
		SporeSwabSourceType:       &SporeSwab{},
		StasisTubeSourceType:      &StasisTube{},
		WaterJarsSourceType:       &WaterJar{},
	}[src]
	if !exists {
		return nil, errors.New(src + " is not a valid entry type")
	}
	return out, nil
}
func typeForSource(src string) (MainCollectionItem, error) {
	out, exists := map[string]MainCollectionItem{
		BagSourceType:             &Bag{},
		FruitSourceType:           &Fruit{},
		FruitingChamberSourceType: &FruitingChamber{},
		GrainJarSourceType:        &GrainJar{},
		LcSyringeSourceType:       &LcSyringe{},
		LcSourceType:              &LiquidCulture{},
		MssSourceType:             &MSS{},
		PlateSourceType:           &Plate{},
		PlugSourceType:            &PlugsJar{},
		SlantSourceType:           &Slant{},
		SporePrintSourceType:      &SporePrint{},
		SporeSwabSourceType:       &SporeSwab{},
		StasisTubeSourceType:      &StasisTube{},
		WaterJarsSourceType:       &WaterJar{},
	}[src]
	if !exists {
		return nil, errors.New(src + " is not a valid entry type")
	}
	return out, nil
}

// Methods

func (b *Bag) SetPerms(field AclField) {
	b.AclField = field
}
func (b Bag) DbId() MainCollectionId {
	return b.Id
}
func (b Bag) EntryType() string {
	return BagSourceType
}
func (b Bag) SourceType() string {
	return BagSourceType
}
func (b Bag) CollectionName() string {
	return BagsCollectionName
}
func (b Bag) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &Bag{}
	err := decodeItem(out, encoded)
	return out, err
}

func (f *Fruit) SetPerms(field AclField) {
	f.AclField = field
}
func (f Fruit) DbId() MainCollectionId {
	return f.Id
}
func (f Fruit) EntryType() string {
	return FruitSourceType
}
func (f Fruit) SourceType() string {
	return FruitSourceType
}
func (f Fruit) CollectionName() string {
	return FruitsCollName
}
func (f Fruit) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &Fruit{}
	err := decodeItem(out, encoded)
	return out, err
}

func (f *FruitingChamber) SetPerms(field AclField) {
	f.AclField = field
}
func (f FruitingChamber) DbId() MainCollectionId {
	return f.Id
}
func (f FruitingChamber) EntryType() string {
	return FruitingChamberSourceType
}
func (f FruitingChamber) SourceType() string {
	return FruitingChamberSourceType
}
func (f FruitingChamber) CollectionName() string {
	return FruitingChamberCollectionName
}
func (f FruitingChamber) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &FruitingChamber{}
	err := decodeItem(out, encoded)
	return out, err
}

func (j *GrainJar) SetPerms(field AclField) {
	j.AclField = field
}
func (j GrainJar) DbId() MainCollectionId {
	return j.Id
}
func (j GrainJar) EntryType() string {
	return GrainJarSourceType
}
func (j GrainJar) SourceType() string {
	return GrainJarSourceType
}
func (j GrainJar) CollectionName() string {
	return GrainJarCollectionName
}
func (j GrainJar) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &GrainJar{}
	err := decodeItem(out, encoded)
	return out, err
}

func (lcs *LcSyringe) SetPerms(field AclField) {
	lcs.AclField = field
}
func (lcs LcSyringe) DbId() MainCollectionId {
	return lcs.Id
}
func (lcs LcSyringe) EntryType() string {
	return LcSyringeSourceType
}
func (lcs LcSyringe) SourceType() string {
	return LcSyringeSourceType
}
func (lcs LcSyringe) CollectionName() string {
	return LcSyringeCollectionName
}
func (lcs LcSyringe) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &LcSyringe{}
	err := decodeItem(out, encoded)
	return out, err
}

func (l *LiquidCulture) SetPerms(field AclField) {
	l.AclField = field
}
func (l LiquidCulture) DbId() MainCollectionId {
	return l.Id
}
func (l LiquidCulture) EntryType() string {
	return LcSourceType
}
func (l LiquidCulture) SourceType() string {
	return LcSourceType
}
func (l LiquidCulture) CollectionName() string {
	return LCCollectionName
}
func (l LiquidCulture) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &LiquidCulture{}
	err := decodeItem(out, encoded)
	return out, err
}

func (M *MSS) SetPerms(field AclField) {
	M.AclField = field
}
func (M MSS) DbId() MainCollectionId {
	return M.Id
}
func (M MSS) EntryType() string {
	return MssSourceType
}
func (M MSS) SourceType() string {
	return MssSourceType
}
func (M MSS) CollectionName() string {
	return MssCollectionName
}
func (M MSS) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &MSS{}
	err := decodeItem(out, encoded)
	return out, err
}

func (p *Plate) SetPerms(field AclField) {
	p.AclField = field
}
func (p Plate) DbId() MainCollectionId {
	return p.Id
}
func (p Plate) EntryType() string {
	return PlateSourceType
}
func (p Plate) SourceType() string {
	return PlateSourceType
}
func (p Plate) CollectionName() string {
	return PlatesCollectionName
}
func (p Plate) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &Plate{}
	err := decodeItem(out, encoded)
	return out, err
}

func (pl *PlugsJar) SetPerms(field AclField) {
	pl.AclField = field
}
func (pl PlugsJar) DbId() MainCollectionId {
	return pl.Id
}
func (pl PlugsJar) EntryType() string {
	return PlugSourceType
}
func (pl PlugsJar) SourceType() string {
	return PlugSourceType
}
func (pl PlugsJar) CollectionName() string {
	return PlugsCollectionName
}
func (pl PlugsJar) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &PlugsJar{}
	err := decodeItem(out, encoded)
	return out, err
}

func (s *Slant) SetPerms(field AclField) {
	s.AclField = field
}
func (s Slant) DbId() MainCollectionId {
	return s.Id
}
func (s Slant) EntryType() string {
	return SlantSourceType
}
func (s Slant) SourceType() string {
	return SlantSourceType
}
func (s Slant) CollectionName() string {
	return SlantsCollectionName
}
func (s Slant) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &Slant{}
	err := decodeItem(out, encoded)
	return out, err
}

func (sp *SporePrint) SetPerms(field AclField) {
	sp.AclField = field
}
func (sp SporePrint) DbId() MainCollectionId {
	return sp.Id
}
func (sp SporePrint) EntryType() string {
	return SporePrintSourceType
}
func (sp SporePrint) SourceType() string {
	return SporePrintSourceType
}
func (sp SporePrint) CollectionName() string {
	return SporePrintCollectionName
}
func (sp SporePrint) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &SporePrint{}
	err := decodeItem(out, encoded)
	return out, err
}

func (sw *SporeSwab) SetPerms(field AclField) {
	sw.AclField = field
}
func (sw SporeSwab) DbId() MainCollectionId {
	return sw.Id
}
func (sw SporeSwab) EntryType() string {
	return SporeSwabSourceType
}
func (sw SporeSwab) SourceType() string {
	return SporeSwabSourceType
}
func (sw SporeSwab) CollectionName() string {
	return SporeSwabCollectionName
}
func (sw SporeSwab) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &SporeSwab{}
	err := decodeItem(out, encoded)
	return out, err
}

func (s *StasisTube) SetPerms(field AclField) {
	s.AclField = field
}
func (s StasisTube) DbId() MainCollectionId {
	return s.Id
}
func (s StasisTube) EntryType() string {
	return StasisTubeSourceType
}
func (s StasisTube) SourceType() string {
	return StasisTubeSourceType
}
func (s StasisTube) CollectionName() string {
	return StasisTubeCollectionName
}
func (s StasisTube) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &StasisTube{}
	err := decodeItem(out, encoded)
	return out, err
}

func (wj *WaterJar) SetPerms(field AclField) {

}
func (wj WaterJar) DbId() MainCollectionId {
	return wj.Id
}
func (wj WaterJar) EntryType() string {
	return WaterJarsSourceType
}
func (wj WaterJar) SourceType() string {
	return WaterJarsSourceType
}
func (wj WaterJar) CollectionName() string {
	return WaterJarsCollectionName
}
func (wj WaterJar) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &WaterJar{}
	err := decodeItem(out, encoded)
	return out, err
}

// Alternate Collection Entry Types

func (batch AgarBatch) CollectionName() string {
	return AgarBatchCollectionName
}
func (batch AgarBatch) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &AgarBatch{}
	err := decodeItem(out, encoded)
	return out, err
}

func (batch *AgarBatch) SetPerms(field AclField) {
	batch.AclField = field
}

func (recipe AgarRecipe) CollectionName() string {
	return AgarRecipesCollectionName
}
func (recipe AgarRecipe) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &AgarRecipe{}
	err := decodeItem(out, encoded)
	return out, err
}

func (recipe *AgarRecipe) SetPerms(field AclField) {
	recipe.AclField = field
}

func (batch GrainBatch) CollectionName() string {
	return GrainBatchCollectionName
}
func (batch GrainBatch) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &GrainBatch{}
	err := decodeItem(out, encoded)
	return out, err
}

func (batch *GrainBatch) SetPerms(field AclField) {
	batch.AclField = field
}

func (recipe LcRecipe) CollectionName() string {
	return LcRecipesCollectionName
}
func (recipe LcRecipe) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &LcRecipe{}
	err := decodeItem(out, encoded)
	return out, err
}

func (recipe *LcRecipe) SetPerms(field AclField) {
	recipe.AclField = field
}

func (run PCRun) CollectionName() string {
	return PcRunCollectionName
}
func (run PCRun) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &PCRun{}
	err := decodeItem(out, encoded)
	return out, err
}

func (run *PCRun) SetPerms(field AclField) {
	run.AclField = field
}

func (p Project) CollectionName() string {
	return ProjectsCollectionName
}
func (p Project) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &Project{}
	err := decodeItem(out, encoded)
	return out, err
}

func (s Sale) CollectionName() string {
	return SalesCollectionName
}
func (s Sale) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &Sale{}
	err := decodeItem(out, encoded)
	return out, err
}

func (s *Sale) SetPerms(field AclField) {
	s.AclField = field
}

func (sp Species) CollectionName() string {
	return SpeciesCollectionName
}
func (sp Species) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &Species{}
	err := decodeItem(out, encoded)
	return out, err
}

func (sp *Species) SetPerms(field AclField) {
	sp.AclField = field
}

func (subsp Subspecies) CollectionName() string {
	return SubspeciesCollectionName
}
func (subsp Subspecies) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &Subspecies{}
	err := decodeItem(out, encoded)
	return out, err
}

func (subsp *Subspecies) SetPerms(field AclField) {
	subsp.AclField = field
}

func (batch SubstrateBatch) CollectionName() string {
	return SubstrateBatchCollectionName
}
func (batch SubstrateBatch) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &SubstrateBatch{}
	err := decodeItem(out, encoded)
	return out, err
}

func (batch *SubstrateBatch) SetPerms(field AclField) {
	batch.AclField = field
}

func (recipe SubstrateRecipe) CollectionName() string {
	return SubstrateRecipesCollectionName
}
func (recipe SubstrateRecipe) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &SubstrateRecipe{}
	err := decodeItem(out, encoded)
	return out, err
}

func (recipe *SubstrateRecipe) SetPerms(field AclField) {
	recipe.AclField = field
}

func (t Transfer) CollectionName() string {
	return TransfersCollName
}
func (t Transfer) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &Transfer{}
	err := decodeItem(out, encoded)
	return out, err
}

func (t *Transfer) SetPerms(field AclField) {
	t.AclField = field
}

func (u User) CollectionName() string {
	return UserCollName
}
func (u User) Decode(encoded *mongo.SingleResult) (CollectionItem, error) {
	out := &User{}
	err := decodeItem(out, encoded)
	return out, err
}
